### ISSUE TITLE
Database sorting always faster than ruby sorting

### ISSUE THREAD

**Issue by nathanallen** [bw-giraffe/project_vagabond#27]
See `app/controllers/entries_controller.rb#L6`, `app/controllers/cities_controller.rb#L4`, `app/controllers/cities_controller.rb#L9`.

``` ruby
@cities = City.all.sort{|a,b| a.name <=> b.name}
```

Querying `all` entries and then sorting them in memory, with ruby, will always be slower than having the database do it for you!

Also, at some point you will need to limit your index to only the 30 most recent entries (rendering 10000000 records is considered a Bad Idea ™).

**Comment by KayvonRanjbar** [comment]
Switched to database sorting
